version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      databasetestcase:

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
    networks:
      databasetestcase:

  tests:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: app
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./resources:/app/resources
      - ./phpunit.xml:/app/phpunit.xml
      - ./composer.json:/app/composer.json
    networks:
      databasetestcase:

networks:
  databasetestcase:

volumes:
  mysqldata:
  pgdata: