name: 'Tests'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: './docker-compose.yml'
          down-flags: '--volumes'
          services: |
            tests